### ISSUE TITLE
Prometheus 2.52.0 rejects values from the jmx reporter 

### ISSUE THREAD

**Issue by mkleen** [crate/jmx_exporter#72]
After an update of Prometheus @goat-ssh reported that the metrics from the JMX reporter are rejected with the warning:

```
Error on ingesting samples with different value but same timestamp" num_dropped=4
```

This is related to a change from 2.52.0  https://github.com/prometheus/prometheus/issues/14089 where values with duplicate timestamps are rejected. We need to ensure that the values produced by the jmx reporter are compatible with the latest Prometheus version.

**Comment by matriv** [comment]
After some investigation and with the help from @WalBeh (Thank you!), it seems that this is not a jmx_exporter issue. jmx_exporter doesn't provide any timestamp on its http api, it's just a list of metric names and values (see for example: https://gist.github.com/matriv/884118f89924174790f62044565e8834), so currently we cannot see how this can affect the restriction introduced to prometheus in its latest version.

I'm closing this issue here, but of course if you find that indeed something should be changed in jmx_exporter to facilitate this new restriction on prometheus, feel free to re-open, and provide the necessary info to proceed.

**Comment by proddata** [comment]
While the origin is probably the MXBean in CrateDB, this will also need a fix in the exporter:
https://github.com/crate/crate/issues/16450

**Comment by matriv** [comment]
Thank you @proddata !
